spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/fp-admin?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    timeout: 1000
    host: localhost
    password: ah43(dd)0
    port: 6379
    database: 1
    lettuce:
      pool:
        max-active: 10 # 最大活跃连接数
        max-idle: 10 # 最大空闲连接
        min-idle: 2 # 最小空闲连接
        max-wait: 6000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      shutdown-timeout: 100

mybatis-plus:
  check-config-location: true # 启动时是否检查mybatis xml文件存在，默认不检查
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 配置sql打印日志

# 自定义fpwag-boot starter配置
fpwag-boot:
  logging:
    enable: true
    print-details: false
  web:
    result:
      enable: true
    exception:
      enable: true
      output-trace: true # 输出异常堆栈
  swagger:
    enable: true
  redis:
    enable: false # 关闭spring cache缓存注解
  oss: # 对象存储配置，使用本地存储
    enable: true
    local:
      enable: true
      endpoint: http://localhost:8899
      bucketName: test # 建议此配置
      contextPath: C:/upload
      persist: true
      del-object: true

sso:
  ignore-urls: /oss/**, /test/** # 仅测试用的
  image-code:
    enable: true
  cors:
    enable: true